// This file will be auto-generated by: supabase gen types typescript
// For now, provide a placeholder that matches our schema

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          avatar_url: string | null;
          gender: 'male' | 'female' | 'other' | 'prefer_not_to_say' | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          first_name: string;
          last_name: string;
          avatar_url?: string | null;
          gender?: 'male' | 'female' | 'other' | 'prefer_not_to_say' | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          avatar_url?: string | null;
          gender?: 'male' | 'female' | 'other' | 'prefer_not_to_say' | null;
          updated_at?: string;
        };
      };
      gyms: {
        Row: {
          id: string;
          name: string;
          logo_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          logo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          logo_url?: string | null;
          updated_at?: string;
        };
      };
      gym_members: {
        Row: {
          id: string;
          gym_id: string;
          user_id: string;
          role: 'member' | 'coach' | 'admin';
          status: 'active' | 'inactive';
          created_at: string;
        };
        Insert: {
          id?: string;
          gym_id: string;
          user_id: string;
          role: 'member' | 'coach' | 'admin';
          status?: 'active' | 'inactive';
          created_at?: string;
        };
        Update: {
          role?: 'member' | 'coach' | 'admin';
          status?: 'active' | 'inactive';
        };
      };
      plans: {
        Row: {
          id: string;
          gym_id: string;
          name: string;
          description: string | null;
          price_cents: number;
          type: 'count' | 'monthly' | 'annual';
          class_count: number | null;
          is_active: boolean;
          stripe_price_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          gym_id: string;
          name: string;
          description?: string | null;
          price_cents: number;
          type: 'count' | 'monthly' | 'annual';
          class_count?: number | null;
          is_active?: boolean;
          stripe_price_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          price_cents?: number;
          type?: 'count' | 'monthly' | 'annual';
          class_count?: number | null;
          is_active?: boolean;
          stripe_price_id?: string | null;
          updated_at?: string;
        };
      };
      plan_programs: {
        Row: {
          plan_id: string;
          program_id: string;
          created_at: string;
        };
        Insert: {
          plan_id: string;
          program_id: string;
          created_at?: string;
        };
        Update: {
          plan_id?: string;
          program_id?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          gym_id: string;
          user_id: string;
          plan_id: string;
          status: 'active' | 'paused' | 'cancelled' | 'expired';
          classes_used: number;
          period_start: string | null;
          period_end: string | null;
          stripe_subscription_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          gym_id: string;
          user_id: string;
          plan_id: string;
          status?: 'active' | 'paused' | 'cancelled' | 'expired';
          classes_used?: number;
          period_start?: string | null;
          period_end?: string | null;
          stripe_subscription_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: 'active' | 'paused' | 'cancelled' | 'expired';
          classes_used?: number;
          period_start?: string | null;
          period_end?: string | null;
          stripe_subscription_id?: string | null;
          updated_at?: string;
        };
      };
      programs: {
        Row: {
          id: string;
          gym_id: string;
          name: string;
          description: string | null;
          start_date: string | null;
          end_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          gym_id: string;
          name: string;
          description?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          updated_at?: string;
        };
      };
      program_enrollments: {
        Row: {
          id: string;
          program_id: string;
          user_id: string;
          status: 'active' | 'inactive';
          created_at: string;
        };
        Insert: {
          id?: string;
          program_id: string;
          user_id: string;
          status?: 'active' | 'inactive';
          created_at?: string;
        };
        Update: {
          status?: 'active' | 'inactive';
        };
      };
      workouts: {
        Row: {
          id: string;
          program_id: string;
          date: string;
          title: string;
          description: string | null;
          format: 'time' | 'amrap';
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          program_id: string;
          date: string;
          title: string;
          description?: string | null;
          format: 'time' | 'amrap';
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          date?: string;
          title?: string;
          description?: string | null;
          format?: 'time' | 'amrap';
          sort_order?: number;
          updated_at?: string;
        };
      };
      workout_stats: {
        Row: {
          id: string;
          workout_id: string;
          user_id: string;
          time_seconds: number | null;
          amrap_rounds: number | null;
          amrap_reps: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workout_id: string;
          user_id: string;
          time_seconds?: number | null;
          amrap_rounds?: number | null;
          amrap_reps?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          time_seconds?: number | null;
          amrap_rounds?: number | null;
          amrap_reps?: number | null;
          notes?: string | null;
          updated_at?: string;
        };
      };
      classes: {
        Row: {
          id: string;
          gym_id: string;
          name: string;
          description: string | null;
          coach_id: string | null;
          capacity: number | null;
          duration_minutes: number;
          start_time: string;
          days_of_week: number[];
          one_off_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          gym_id: string;
          name: string;
          description?: string | null;
          coach_id?: string | null;
          capacity?: number | null;
          duration_minutes?: number;
          start_time: string;
          days_of_week?: number[];
          one_off_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          coach_id?: string | null;
          capacity?: number | null;
          duration_minutes?: number;
          start_time?: string;
          days_of_week?: number[];
          one_off_date?: string | null;
          updated_at?: string;
        };
      };
      class_occurrences: {
        Row: {
          id: string;
          class_id: string;
          date: string;
          start_time: string;
          coach_id: string | null;
          is_cancelled: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          class_id: string;
          date: string;
          start_time: string;
          coach_id?: string | null;
          is_cancelled?: boolean;
          created_at?: string;
        };
        Update: {
          coach_id?: string | null;
          is_cancelled?: boolean;
        };
      };
      class_signups: {
        Row: {
          id: string;
          occurrence_id: string;
          user_id: string;
          checked_in: boolean;
          checked_in_at: string | null;
          checked_in_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          occurrence_id: string;
          user_id: string;
          checked_in?: boolean;
          checked_in_at?: string | null;
          checked_in_by?: string | null;
          created_at?: string;
        };
        Update: {
          checked_in?: boolean;
          checked_in_at?: string | null;
          checked_in_by?: string | null;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
